version: '3.7'

services:
  postgres:
    image: postgres:14.0
    container_name: monolith_postgres
    ports:
      - "5432:5432"
    environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: monolith
